---
title: "Data Analysis"
output: html_notebook
---
```{r}
library(ggplot2)
library(readr)

library(extrafont) 
library(tidyverse)

# execute once to add fonts:
# font_import() 

loadfonts(device='win')
windowsFonts("Latex" = windowsFont("CMU Serif"))

CTDC.2 = read_csv("../../Datasets/CTDC_Complete.csv")
```



Visuals for DTM Stage

```{r}
CTDC.2$citizenshipDTM = as.factor(CTDC.2$citizenshipDTM)
CTDC.2$exploitationDTM = as.factor(CTDC.2$exploitationDTM)
```


DTM Stages Data
```{r}
library(gridExtra)

# Citizenship DTM Barplot
cit_dtm_plot = ggplot(CTDC.2, aes(citizenshipDTM)) +
  geom_bar() + theme_grey(base_size = 16) +
  theme(axis.text = element_text(size = 9),
    text = element_text(family = "Latex", size = 15)) + 
   scale_fill_grey() +
  labs(x = "Citizenship DTM Stage", y = "Count")

# Exploit DTM Barplot
exp_dtm_plot = ggplot(CTDC.2, aes(exploitationDTM)) +
  geom_bar() + theme_grey(base_size = 16) +
  theme(axis.text = element_text(size = 9),
    text = element_text(family = "Latex", size = 15),
    axis.ticks.y=element_blank(),
    axis.text.y=element_blank()) + 
   scale_fill_grey() +
  labs(x = "Exploitation DTM Stage", y = element_blank())

#merge both plots within one grid
g <- gridExtra::grid.arrange(cit_dtm_plot, exp_dtm_plot, ncol = 2)
ggsave(file='./Graphics/DTMStagesBarplot.png', g, width = 8, height = 4)#saves g
```

Country for Each Stage

```{r}
# Citizenship DTM Barplot
cit_country_plot = ggplot(CTDC.2, aes(citizenshipDTM, fill = citizenship)) +
  geom_bar(position="dodge", width=0.9) + theme_grey(base_size = 16) +
  theme(axis.text = element_text(size = 9),
    text = element_text(family = "Latex", size = 15),
    legend.position = "none") + 
   scale_fill_manual(values=rep("#605c5c", 28)) +
  labs(x = "Citizenship DTM Stage", y = "Count of Each Country")


exp_country_plot = ggplot(CTDC.2,aes(exploitationDTM,
                                     fill = CountryOfExploitation)) +
  geom_bar(position="dodge", width=0.9) + theme_grey(base_size = 16) +
  theme(axis.text = element_text(size = 9),
    text = element_text(family = "Latex", size = 15),
    axis.ticks.y=element_blank(),
    axis.text.y=element_blank(),
    legend.position = "none") + 
   scale_fill_manual(values=rep("#605c5c", 32)) +
  labs(x = "Exploitation DTM Stage", y = element_blank())

#merge both plots within one grid
g <- gridExtra::grid.arrange(cit_country_plot, exp_country_plot, ncol = 2)
ggsave(file='./Graphics/CountryCountBarplot.png', g, width = 8, height = 4)
```

Find overpowering stage 5 country

```{r}
# Citizenship DTM Country
t = table(CTDC.2[CTDC.2$citizenshipDTM == 5,]$citizenship)
t[t == max(t)]

# Exploitation DTM Country
t = table(CTDC.2[CTDC.2$exploitationDTM == 5,]$CountryOfExploitation)
t[t == max(t)]
```

Comparing Russia to Other stage 5 exploitation Chi Square:

```{r}
stage5exp = CTDC.2[CTDC.2$exploitationDTM == 5,]
not_RU = which(stage5exp$CountryOfExploitation != 'RU')
stage5exp$CountryOfExploitation[not_RU] = 'N_RU'

c = chisq.test(stage5exp$CountryOfExploitation, stage5exp[[5]])
c
```


```{r, warning = F}
#Initialize Dataframe
chisq_dataframe = data.frame(VariableName = c(1),
                             ChiSquared = c(1),
                             PValue = c(1))


for (i in c(1:ncol(stage5exp))){
  #Remove columns for country names and citizenship dtm
  #----------------------
  ignored_columns = c('citizenship', "CountryOfExploitation",
                      'citizenshipDTM', 'exploitationDTM')
  
  # If columns has 1 unique value, then ignore
  
  if (length(unique(stage5exp[[i]]))==1){
    ignored_columns = append(ignored_columns, names(stage5exp)[i])
  }
  
  # If column isnt in ignored columns
  if (!(names(stage5exp)[i] %in% ignored_columns)){
    c = chisq.test(stage5exp$CountryOfExploitation, stage5exp[[i]])
    
    # Add Row To Table
    chisq_dataframe[nrow(chisq_dataframe) + 1,] = 
    c(names(stage5exp)[i],c$statistic, c$p.value)
  }
  


}
# Change Class and Remove Initial Row
chisq_dataframe$ChiSquared = as.numeric(chisq_dataframe$ChiSquared)
chisq_dataframe$PValue = as.numeric(chisq_dataframe$PValue)
chisq_dataframe = chisq_dataframe[-c(1),]

write.csv(chisq_dataframe, "./Graphics/ChiSquareDF1.csv")
```





```{r}
ggplot(CTDC.2, aes(citizenshipDTM, fill = exploitationDTM)) +
  geom_bar() + theme_grey(base_size = 16) +
  theme(axis.text = element_text(size = 9),
    text = element_text(family = "Latex", size = 15)) + 
   scale_fill_grey() +
  labs(x = "Citizenship DTM Stage", y = "Count", fill = "Exploitation DTM")
  
ggsave(file='./Graphics/DTMStage1.png', width = 8, height = 4)
```

Count how many cases have same citizenship and exploitation country.
```{r}
nrow(CTDC.2[CTDC.2$citizenship == CTDC.2$CountryOfExploitation,])
nrow(CTDC.2)
nrow(CTDC.2[CTDC.2$citizenship == CTDC.2$CountryOfExploitation,])/nrow(CTDC.2)
```


Same Country
```{r}
diff_country = CTDC.2[!(CTDC.2$citizenship == CTDC.2$CountryOfExploitation),]

ggplot(diff_country, aes(citizenshipDTM, fill = exploitationDTM)) +
  geom_bar() + theme_grey(base_size = 16) +
  theme(axis.text = element_text(size = 9),
    text = element_text(family = "Latex", size = 15)) + 
   scale_fill_grey() +
  labs(x = "Citizenship DTM Stage", y = "Count", fill = "Exploitation DTM")
  
ggsave(file='./Graphics/Different_CountryDTM.png', width = 8, height = 4)
```

Correlation Plot

```{r}
#Select Numeric Only
cor_df = CTDC.2[sapply(CTDC.2, class) != 'character']
cor_df$citizenshipDTM = as.numeric(cor_df$citizenshipDTM)
cor_df$exploitationDTM = as.numeric(cor_df$exploitationDTM)

library("Hmisc") # Gives P-Values for correlation
res2 <- rcorr(as.matrix(cor_df))


corr = res2$r # Correlations
corr_p = res2$P # P-values
```

Correlation Plot
```{r}
library(ggcorrplot)
library(ggplot2)

ggcorrplot(corr, colors = c("#242424", "#E7E7E7", "#242424"),
           tl.cex = 11, tl.srt = 90, show.diag = F,
          p.mat = corr_p, legend.title = "Correlation",
          ggtheme = ggplot2::theme_classic) +
  
  theme(text = element_text(family = "Latex", size = 12),
        axis.text.x = element_text(vjust = 0.1, hjust = 1),
        panel.background = element_rect(fill = '#242424'))

ggsave(file='./Graphics/CorrPlot.png', width = 7, height = 7)
```

More Visualizations

```{r}

```





Binary Percentage Visualization

```{r}
# Create Binary Percentage Dataframe
bin_perc <- CTDC.2 %>% group_by(exploitationDTM) %>% 
  summarise(across(names(CTDC.2[5:23]),sum),
            .groups = 'drop') %>%
  as.data.frame()

bin_perc = (bin_perc/nrow(CTDC.2))[2:ncol(bin_perc)]
```


```{r}
# Gather Dataframe and Add DTM Stages

gath <- bin_perc %>%
  as_data_frame()%>%
  gather(key = "variable", value = "value")

gath$exploitationDTM = rep(c(2,3,4,5),times = nrow(gath)/4)
```

Create Facet Plot
```{r}
# Make Facet Plot
ggplot(gath, aes(x = exploitationDTM,
           y = value)) +
    facet_wrap(~ variable, ncol = 3) +
    geom_bar(stat = "identity",
           position = "dodge") + theme_grey(base_size = 16) +
  theme(axis.text = element_text(size = 9),
    text = element_text(family = "Latex", size = 15)) + 
   scale_fill_grey()+
  labs(y= "Proportion", x = "Exploitation Country DTM Stage",
       title =  "Proportion of Type & Stage Out Of All Cases")

ggsave(file='./Graphics/FacetPlot1.png', width = 8.5, height = 10)
```

